// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfruXeWimt3iNsu2IqVsU4e1GBxDUTcz4',
    appId: '1:300685608803:web:ce1883050706d104c67556',
    messagingSenderId: '300685608803',
    projectId: 'vigtask-app',
    authDomain: 'vigtask-app.firebaseapp.com',
    storageBucket: 'vigtask-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9bTFJXuk2nK5XMjsBfk_Ha1bzIMEJgac',
    appId: '1:300685608803:android:27cd996345892a5ec67556',
    messagingSenderId: '300685608803',
    projectId: 'vigtask-app',
    storageBucket: 'vigtask-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWXoYXjCL12yQzAg3W4sNhOt0zFm9zcVE',
    appId: '1:300685608803:ios:2561c7e29ea6bc75c67556',
    messagingSenderId: '300685608803',
    projectId: 'vigtask-app',
    storageBucket: 'vigtask-app.firebasestorage.app',
    iosBundleId: 'com.vigtask.app',
  );
}
